# Numpy

## Number + Python
- 행렬이나 대규모 다차원 배열을 쉽게 처리
- 계산과학분야의 복잡한 연산
- Scipy나 Matplotlib, Pandas 등으로 복잡한 연산 가능

## ndarray class
- 배열을 이용한 벡터화연산
- 배열에는 모두 동일한 자료형만 저장 가능
- 메모리에 연속적으로 저장
- 일반적으로 리스트보다 빠른것으로 간주
- 벡터계산 가능

In [2]:
import numpy as np
a = [1,2,3]
a1 = np.array([1,2,3])   # 1-D array 생성
print(a * 2)             # a의 요소가 2번 출력
print(a1 *2)             # a1의 각 요소에 X2

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [4]:
type(a1)

numpy.ndarray

In [23]:
a1.shape

(3,)

### 2-D array / 3-D array 생성

In [10]:
a2 = np.array([['a','b','c'],[1,2,3]])
a2

array([['a', 'b', 'c'],
       ['1', '2', '3']], dtype='<U1')

In [11]:
len(a2)                     # a2의 행 갯수

2

In [20]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[11,12,13],[14,15,16],[17,18,19]],
              [[21,22,23],[24,25,26],[27,28,29]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [21]:
a3.shape     # 깊이 3 ,행 3, 열 3

(3, 3, 3)

In [24]:
a3.ndim      # 차원 

3

### 배열 생성
1. np.ones
2. np.zeros
3. np.arange
4. np.random.random
    - np.random.random(a,b (배열의 크기))
    - np.random.randint(a,b,c)
5. np.linspace(시작, 끝, 숫자갯수)

#### 1. np.ones
- 배열의 모든 원소를 1로 생성

In [27]:
ar_1 = np.ones((3,5))     # 3행 5열
ar_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 2. np.zeros
- 배열의 모든 원소를 0으로 생성

In [28]:
ar_0 = np.zeros((2,7))     # 2행 7열
ar_0

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 3. np.arange
- 연속된 숫자로 배열 생성

In [32]:
ar_arange = np.arange(1,20,3)    # 1부터 20미만까지 3간격으로
ar_arange

array([ 1,  4,  7, 10, 13, 16, 19])

#### 4. np.random.random
- 0에서 1사이의 실수값을 요소로 하는 배열 생성

In [38]:
ar_random = np.random.random((6,3))
ar_random

array([[0.31874242, 0.82890888, 0.40833093],
       [0.16231001, 0.55314318, 0.9261419 ],
       [0.02840441, 0.31514126, 0.90581132],
       [0.19587483, 0.38667424, 0.01177345],
       [0.799988  , 0.57826845, 0.75596771],
       [0.04652645, 0.64183906, 0.20153357]])

#### 4.1 np.random.random( a, b (배열의 크기))
- 실수 a와 b 사이의 수로 배열 생성

In [65]:
np.random.uniform(10,11,(4,3))    

array([[10.12290546, 10.5958889 , 10.1346376 ],
       [10.0525314 , 10.43145584, 10.17977053],
       [10.42058969, 10.67919332, 10.25086245],
       [10.11688245, 10.13108465, 10.83579392]])

#### 4.2 np.random.ranint(a,b,c)
- a부터 b까지 랜덤으로 c개로 배열 생성

In [82]:
ar_ran = np.random.randint(0,10,5)
ar_ran

array([2, 2, 3, 4, 3])

#### 5. np.linspace(시작, 끝, 숫자갯수)
- 동일 간격으로 등분한 배열 생성

In [69]:
ar1 = np.linspace(0,10,4)
ar1

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [74]:
ar2 = np.linspace(0,10,5)
ar2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### reshape
- 배열의 모양 변경

In [40]:
ar_random.reshape(9,2)      # 6열 3행 --> 9행 2열로 reshape

array([[0.31874242, 0.82890888],
       [0.40833093, 0.16231001],
       [0.55314318, 0.9261419 ],
       [0.02840441, 0.31514126],
       [0.90581132, 0.19587483],
       [0.38667424, 0.01177345],
       [0.799988  , 0.57826845],
       [0.75596771, 0.04652645],
       [0.64183906, 0.20153357]])

### Transpose
- 행과 열을 교체 ar.T

In [48]:
ar_t = np.arange(100).reshape(5,2,10)
ar_t

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [49]:
ar_t.T

array([[[ 0, 20, 40, 60, 80],
        [10, 30, 50, 70, 90]],

       [[ 1, 21, 41, 61, 81],
        [11, 31, 51, 71, 91]],

       [[ 2, 22, 42, 62, 82],
        [12, 32, 52, 72, 92]],

       [[ 3, 23, 43, 63, 83],
        [13, 33, 53, 73, 93]],

       [[ 4, 24, 44, 64, 84],
        [14, 34, 54, 74, 94]],

       [[ 5, 25, 45, 65, 85],
        [15, 35, 55, 75, 95]],

       [[ 6, 26, 46, 66, 86],
        [16, 36, 56, 76, 96]],

       [[ 7, 27, 47, 67, 87],
        [17, 37, 57, 77, 97]],

       [[ 8, 28, 48, 68, 88],
        [18, 38, 58, 78, 98]],

       [[ 9, 29, 49, 69, 89],
        [19, 39, 59, 79, 99]]])

### 슬라이싱
- 1차원 배열 : 리스트와 동일
- N차원 배열 : ','로 구별하여 연결

In [52]:
ar_s1 = np.arange(10)
ar_s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print(ar_s1[2:8])

[2 3 4 5 6 7]


In [55]:
ar_s2 = np.arange(30).reshape(3,2,5)
ar_s2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [56]:
ar_s2[0:,0:1,2:4]

array([[[ 2,  3]],

       [[12, 13]],

       [[22, 23]]])

### 다차원 배열을 1차원 배열로 전환
1. np.ravel(ar)
2. ar.flatten()

#### 1. np.ravel(ar)

In [58]:
ar = np.arange(27).reshape(3,3,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
ar1 = np.ravel(ar)       # 3 X 3 X 3 배열을 1차원으로 변환
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [63]:
ar2 = ar.flatten()      # 3 X 3 X 3 배열을 1차원으로 변환  
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### 배열의 사칙 연산

In [75]:
ar = np.array([1,3,5,7,9,11,13])
ar >= 10

array([False, False, False, False, False,  True,  True])

In [81]:
ar[ar>3]

array([ 5,  7,  9, 11, 13])

In [93]:
ar = np.array([0,2,3,4,5,6,7,8,9])
ar1 = np.arange(9)
ar==ar1

array([ True, False, False, False, False, False, False, False, False])

### Broadcasting
- 행렬끼리 연살할 때 크기가 다른 경우 이를 알아서 확대 해주는 기능

In [84]:
ar0 = np.arange(10).reshape(2,5)
ar1 = np.arange(20).reshape(2,2,5)
ar0

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
ar1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [86]:
ar0+ar1

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]]])

In [97]:
ar = np.arange(30).reshape(3,2,5)
ar

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [99]:
np.min(ar[1:,:,1:3])     # 1행부터 ~ , 각 행의 모든 행, 그 행의 1~2번째 열 값

11

### np.argmin(ar)
- 1차원으로 늘여놓은 상태에서 가장 작은 값이 몇 번째에 있는지 알려줌 (0부터 시작)

In [101]:
ar = np.array([[9,8,7],[5,4,3],[5,4,1]])
np.argmin(ar)

8

### sum / mean / median
1. sum : 모든 요소의 합
2. mean : 모든 요소의 평균
3. median : 모든 요소 중 가운데 값

In [102]:
ar = np.arange(1,31,2).reshape(3,5)
ar

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [103]:
print(np.sum(ar))
print(np.mean(ar))
print(np.median(ar))

225
15.0
15.0


### np로 파일 읽어오기
- np.loadtxt('경로')

In [105]:
a = np.loadtxt('c:/data/file01.txt')

In [106]:
a

array([[10., 11., 12., 13., 14.],
       [25., 26., 27., 28., 29.],
       [ 5.,  6.,  7.,  8.,  9.],
       [20., 21., 22., 23., 24.],
       [15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.]])