# Numpy
## Number + Python
- 수치해석용 파이썬 패키지

## Numpy array
- 모든 원소가 같은 자료형이어야 한다
- 원소이 갯수를 바꿀 수 없다
- 배열을 이용한 벡터화 연산

### 1차원 배열 만들기

In [3]:
import numpy as np
ar = np.array([1,2,3,4,5])
print(ar)
print(type(ar))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 벡터화 연산

In [6]:
# 모든 원소에 X2를 해주기 - list
data = [1,2,3,4,5]
ans = []
for i in data:
    ans.append(i * 2)
ans

[2, 4, 6, 8, 10]

In [7]:
# 모든 원소에 X2를 array를 이용하면 쉽게 가능
ar = np.array([1,2,3,4,5])
ar1 = ar*2
ar1

array([ 2,  4,  6,  8, 10])

### Array에 다양한 수학 연산 적용

In [67]:
ar = np.array([1,2,3,4,5])
ar * 2

array([ 2,  4,  6,  8, 10])

In [68]:
ar = np.array([1,2,3,4,5])
ar == 2

array([False,  True, False, False, False])

In [69]:
ar = np.array([1,2,3,4,5])
ar > 3

array([False, False, False,  True,  True])

In [70]:
ar[ar>3]

array([4, 5])

### 2차원 배열 만들기
- ndarray (N-dimensional Array)

In [15]:
# 2차원 배열 생성
ar = np.array([[1,1,1],[2,2,2]])
ar

array([[1, 1, 1],
       [2, 2, 2]])

#### 행의 갯수

In [16]:
len(ar)

2

#### 열의 갯수

In [17]:
len(ar[0])

3

### 3차원 배열 만들기

In [18]:
ar = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4,]]])
ar

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [23]:
print('len(ar) : ', len(ar), '\n','len(ar[0]) : ', len(ar[0]))

len(ar) :  2 
 len(ar[0]) :  2


### 배열의 차원과 크기 알아내기
1. ndim - 배열의 차원
2. shape - 배열의 크기

In [31]:
ar = np.array([1,2,3,4,5])
print(ar)
print('배열의 차원 ',ar.ndim)
print('배열의 크기 : ',ar.shape)

[1 2 3 4 5]
배열의 차원  1
배열의 크기 :  (5,)


In [32]:
ar = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(ar)
print('배열의 차원 ',ar.ndim)
print('배열의 크기 : ',ar.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
배열의 차원  2
배열의 크기 :  (3, 5)


### 배열 생성하기
1. np.ones
2. np.zeros
3. np.arange
4. np.random

1. np.ones
    - 배열의 모든 원소가 1인 배열 생성

In [38]:
ar = np.ones((3,6))
ar

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

2. np.zeros
    - 배열의 모든 원소가 0인 배열 생성

In [41]:
ar = np.zeros((2,5))
ar

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. np.arange
    - 연속된 숫자를 원소로 한 배열 생성

In [65]:
# 10과 29 사이 숫자의 간격을 4로 설정
ar = np.arange(10,30,4)
ar

array([10, 14, 18, 22, 26])

In [48]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### reshape
- 배열의 차원을 바꿔준다

In [49]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4.np.random.random
    - 0부터 1까지의 실수를 원소로 한 배열 생성

In [53]:
ar = np.random.random((3,5))
ar

array([[0.16801839, 0.06997167, 0.06426528, 0.28832459, 0.40300499],
       [0.66939952, 0.06554562, 0.69052779, 0.89333889, 0.22085302],
       [0.79660632, 0.8592774 , 0.82095706, 0.9799463 , 0.669733  ]])

In [76]:
ar = np.random.randint(1,100, (2,3,5)) # 1 ~ 100 사이의 정수로 2 X 3 X 5 array 생성
ar

array([[[80, 88, 77, 63, 83],
        [39, 63, 20, 55, 89],
        [64, 59, 92, 98, 26]],

       [[82, 87, 54, 31, 46],
        [73, 13, 73, 10, 63],
        [32, 29, 74, 24, 45]]])

### Transpose
- 행과 열을 바꿔준다
- ar.T

In [55]:
ar = np.array([[1,1,1],[2,2,2]])
ar

array([[1, 1, 1],
       [2, 2, 2]])

In [56]:
ar.T

array([[1, 2],
       [1, 2],
       [1, 2]])

In [58]:
ar = np.arange(0,15).reshape(3,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
ar.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### 다차원 배열을 1차원 배열로 변환
1. np.revel(ar1)
2. ar1.flatten()

In [61]:
ar = np.arange(0,30).reshape(3,2,5)
ar

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [63]:
np.ravel(ar)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
ar.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### 배열의 슬라이싱
- 1차원 배열 : 리스트와 동일
- N차원 배열 : ','로 구별하여 연결

In [82]:
ar = np.arange(30).reshape(2,3,5)
ar

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [83]:
ar[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [85]:
ar[1:,:1,:2]

array([[[15, 16]]])

## sum은 axis를 기준으로 행과 열의 합계산이 가능
- axis = 0  각 열의 모든 값에 대한 연산

In [88]:
ar = np.arange(1,31,2).reshape(3,5)
ar

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [93]:
np.sum(ar, axis=0)  # 각 열에 해당하는 값들을 각 열별로 모두 더한 값

array([33, 39, 45, 51, 57])

In [94]:
np.sum(ar, axis = 1)   # 각 행에 있는 값들을 모두 더한 값

array([ 25,  75, 125])

In [92]:
np.sum(ar[1:], axis=0) # 11 13 15 17 19 행과 21 23 25 27 29 행의 같은 열끼리 더한 값

array([32, 36, 40, 44, 48])

In [118]:
ar = np.array([[[0.5,2,4,-5],[0.7,9,3,0.7],[8,1,-2,0.3]],[[1.2,4,2,-9],[8,3,2,1],[2,8,5,-1]],[[3,9,6,0.8],[0.9,-1,3,4],[2,5,7,9]]])
ar

array([[[ 0.5,  2. ,  4. , -5. ],
        [ 0.7,  9. ,  3. ,  0.7],
        [ 8. ,  1. , -2. ,  0.3]],

       [[ 1.2,  4. ,  2. , -9. ],
        [ 8. ,  3. ,  2. ,  1. ],
        [ 2. ,  8. ,  5. , -1. ]],

       [[ 3. ,  9. ,  6. ,  0.8],
        [ 0.9, -1. ,  3. ,  4. ],
        [ 2. ,  5. ,  7. ,  9. ]]])

In [121]:
print('합 : ',np.sum(ar))   # ar.sum()도 가능
print('평균 : ',np.mean(ar))
print('중간값 : ',np.median(ar))

합 :  97.1
평균 :  2.697222222222222
중간값 :  2.0


In [106]:
print('2번째 행렬의 합, 최소값, 최대값')
print('합 : ',np.sum(ar[1]))
print('최소값 : ',np.min(ar[1]))
print('최대값 : ',np.max(ar[1]))

2번째 행렬의 합, 최소값, 최대값
합 :  26.2
최소값 :  -9.0
최대값 :  8.0


In [131]:
slicing = ar[0:,0:,1:3]
slicing

array([[[ 2.,  4.],
        [ 9.,  3.],
        [ 1., -2.]],

       [[ 4.,  2.],
        [ 3.,  2.],
        [ 8.,  5.]],

       [[ 9.,  6.],
        [-1.,  3.],
        [ 5.,  7.]]])

In [128]:
print('1,4번째 열을 제외한 부분 행렬의 최대, 최소, 평균, 중간값')
print('최대 : ',np.max(slicing))
print('최소 : ',np.min(slicing))
print('평균 : ',np.mean(slicing))
print('중간값 : ',np.median(slicing))

1,4번째 열을 제외한 부분 행렬의 최대, 최소, 평균, 중간값
최대 :  9.0
최소 :  -2.0
평균 :  3.888888888888889
중간값 :  3.5


행렬곱 (내적)

In [135]:
a = np.arange(1,21,2).reshape(2,5)
b = np.arange(3,13,1).reshape(5,2)
print(a,'\n-',b)
np.dot(a,b) # or a@b

[[ 1  3  5  7  9]
 [11 13 15 17 19]] 
- [[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


array([[215, 240],
       [565, 640]])

## 행렬곱 (내적)
- abT = bTaT
- 특징

In [140]:
a = np.arange(0,31,2).reshape(4,4)

In [143]:
b = np.arange(1,32,2).reshape(4,4)

In [144]:
c = np.arange(2,33,2).reshape(4,4)

In [146]:
a@b

array([[ 236,  260,  284,  308],
       [ 652,  740,  828,  916],
       [1068, 1220, 1372, 1524],
       [1484, 1700, 1916, 2132]])

In [147]:
b@a

array([[ 272,  304,  336,  368],
       [ 656,  752,  848,  944],
       [1040, 1200, 1360, 1520],
       [1424, 1648, 1872, 2096]])

In [145]:
a@b == b@a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [148]:
a@(b+c)

array([[ 484,  532,  580,  628],
       [1348, 1524, 1700, 1876],
       [2212, 2516, 2820, 3124],
       [3076, 3508, 3940, 4372]])

In [149]:
a@b + a@c

array([[ 484,  532,  580,  628],
       [1348, 1524, 1700, 1876],
       [2212, 2516, 2820, 3124],
       [3076, 3508, 3940, 4372]])

In [150]:
a@(b+c) == a@b + a@c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [151]:
(a+b)@c == a@c + b@c

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [152]:
(a@b).T == (b.T)@(a.T)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [155]:
385**(1/2)

19.621416870348583

## sort
- 배열의 오름차순으로 정렬
- ar.sort() : ar을 정렬(반환 x)
- np.random.shuffle()은 배열의 행 순서만 섞는다
- 2차원 이상인 경우 axis에 따라 정렬이 가능

In [157]:
ar = np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [159]:
np.random.shuffle(ar)

In [160]:
ar

array([ 8, 11,  3,  1, 14, 12, 10,  2,  4, 13,  9,  6,  0,  5,  7])

In [161]:
ar2 = np.sort(ar)

In [162]:
ar

array([ 8, 11,  3,  1, 14, 12, 10,  2,  4, 13,  9,  6,  0,  5,  7])

In [163]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [164]:
ar3=np.sort(ar, axis=0)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 차원 / 중복 무시하고 값들 1차원으로 정렬하기
- np.unique(ar) : ar의 값들을 정렬(중복제거)하여 1차원으로 반환

In [165]:
ar= np.random.randint(-10,10,(2,5))
ar

array([[ 6, -1,  1, -3,  4],
       [-7,  0,  3,  5,  5]])

In [166]:
np.unique(ar)

array([-7, -3, -1,  0,  1,  3,  4,  5,  6])

1~100의 정수로 (10,10) 행렬을 생성한 후, np.random.shuffle()을 이용하여 행렬을 섞은 다음, 행렬을 정렬

In [169]:
ar = np.random.randint(1,101,(10,10))
ar

array([[ 4, 25, 14, 73, 27, 34, 78, 26, 92, 50],
       [70, 87, 83, 50, 25, 11, 59,  9, 41, 82],
       [88, 39, 95, 90,  5, 70, 75, 32,  4, 32],
       [ 7, 99, 66, 28, 85, 24, 73, 65, 37, 53],
       [53, 98, 23,  3, 48, 15, 41, 89, 26, 39],
       [ 9, 48, 46, 63, 31, 19, 41, 80, 83, 35],
       [73, 78, 24, 43,  3, 35, 20,  7, 65,  6],
       [67, 15, 89, 25, 54, 40, 79, 88, 78, 14],
       [23, 58, 53, 73, 82, 34, 30, 31, 51, 41],
       [72, 82,  6, 62, 46, 57, 50,  5, 18, 99]])

In [176]:
np.random.shuffle(ar)

In [177]:
ar

array([[ 9, 48, 46, 63, 31, 19, 41, 80, 83, 35],
       [ 4, 25, 14, 73, 27, 34, 78, 26, 92, 50],
       [72, 82,  6, 62, 46, 57, 50,  5, 18, 99],
       [23, 58, 53, 73, 82, 34, 30, 31, 51, 41],
       [53, 98, 23,  3, 48, 15, 41, 89, 26, 39],
       [67, 15, 89, 25, 54, 40, 79, 88, 78, 14],
       [70, 87, 83, 50, 25, 11, 59,  9, 41, 82],
       [ 7, 99, 66, 28, 85, 24, 73, 65, 37, 53],
       [73, 78, 24, 43,  3, 35, 20,  7, 65,  6],
       [88, 39, 95, 90,  5, 70, 75, 32,  4, 32]])

In [178]:
np.sort(ar)

array([[ 9, 19, 31, 35, 41, 46, 48, 63, 80, 83],
       [ 4, 14, 25, 26, 27, 34, 50, 73, 78, 92],
       [ 5,  6, 18, 46, 50, 57, 62, 72, 82, 99],
       [23, 30, 31, 34, 41, 51, 53, 58, 73, 82],
       [ 3, 15, 23, 26, 39, 41, 48, 53, 89, 98],
       [14, 15, 25, 40, 54, 67, 78, 79, 88, 89],
       [ 9, 11, 25, 41, 50, 59, 70, 82, 83, 87],
       [ 7, 24, 28, 37, 53, 65, 66, 73, 85, 99],
       [ 3,  6,  7, 20, 24, 35, 43, 65, 73, 78],
       [ 4,  5, 32, 32, 39, 70, 75, 88, 90, 95]])

1~30의 정수로 (3,10) 행렬을 생성, np.random.shuffle()을 이용하여 행렬을 섞음, axis값을 바꿔가며 정렬

In [191]:
ar = np.random.randint(1,31,(3,10))
ar

array([[ 8,  6, 10, 12,  9,  1, 20,  4, 22,  5],
       [14,  8, 22,  7, 30, 28, 18, 28, 23,  6],
       [22, 10, 21,  3, 22,  2, 10,  2,  6, 18]])

In [192]:
# 각 행들의 순서가 바뀐다
np.random.shuffle(ar)
ar

array([[22, 10, 21,  3, 22,  2, 10,  2,  6, 18],
       [ 8,  6, 10, 12,  9,  1, 20,  4, 22,  5],
       [14,  8, 22,  7, 30, 28, 18, 28, 23,  6]])

In [193]:
# 각 열의 값들을 sort
np.sort(ar, axis=0)

array([[ 8,  6, 10,  3,  9,  1, 10,  2,  6,  5],
       [14,  8, 21,  7, 22,  2, 18,  4, 22,  6],
       [22, 10, 22, 12, 30, 28, 20, 28, 23, 18]])

In [194]:
# 각 행의 값들을 sort
np.sort(ar, axis=1)

array([[ 2,  2,  3,  6, 10, 10, 18, 21, 22, 22],
       [ 1,  4,  5,  6,  8,  9, 10, 12, 20, 22],
       [ 6,  7,  8, 14, 18, 22, 23, 28, 28, 30]])

In [195]:
ar = np.random.randint(1,50, (4,3))
ar

array([[41,  1, 40],
       [19, 27,  8],
       [42, 33, 34],
       [18, 26,  6]])

#1


In [189]:
ar1 = np.random.shuffle(ar)
ar1

In [188]:
ar

array([[ 4, 15, 16],
       [35, 33, 30],
       [31, 20,  7],
       [35, 29, 35]])

In [210]:
ar = np.arange(100).reshape(10,10)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
np.random.shuffle(ar)
ar

TypeError: shuffle() takes no keyword arguments

In [209]:
ar1 = np.sort(ar)
ar1

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [203]:
np.argmin(ar1)

10

In [204]:
np.argmax(ar1)

99

In [205]:
ar22 = ([[5,13,20,24,14,24],[30,6,19,30,4,2],[15,1,16,15,1,1],[26,26,16,8,24,15],[4,27,17,2,14,19]])

In [213]:
# 전체 합, 평균, 중간값
np.sum(ar22)

438

In [214]:
np.mean(ar22)

14.6

In [215]:
np.median(ar22)

15.0

## Deep Copy & Shallow Copy
- Deep Copy : 새롭게 생성
- Shallow Copy : 같은 곳을 참고
     - 복사된 곳에서 값을 수정하면 원본도 수정

In [218]:
ar = np.arange(10).reshape(5,2)
ar

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [226]:
ar1 = ar   # Shallow Copy
ar1[0][1] = 77
ar1

array([[ 0, 77],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [221]:
ar

array([[ 0, 77],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [225]:
ar = np.arange(10).reshape(5,2)
ar1 = ar.copy()   # Deep Copy
ar1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [223]:
ar1[0][1] = 888
ar1

array([[  0, 888],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [224]:
ar

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 행렬을 텍스트파일로 저장하거나 불러오는 기능

In [227]:
ar = np.arange(30).reshape(6,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [228]:
np.random.shuffle(ar)
ar

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

In [229]:
np.savetxt('file01.txt', ar)

In [230]:
ar2 = np.loadtxt('file01.txt')
ar2

array([[10., 11., 12., 13., 14.],
       [25., 26., 27., 28., 29.],
       [ 5.,  6.,  7.,  8.,  9.],
       [20., 21., 22., 23., 24.],
       [15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [232]:
np.savetxt('C:/data/file01.txt',ar2)

In [233]:
ar3 = np.loadtxt('C:/data/file01.txt')

In [234]:
ar3

array([[10., 11., 12., 13., 14.],
       [25., 26., 27., 28., 29.],
       [ 5.,  6.,  7.,  8.,  9.],
       [20., 21., 22., 23., 24.],
       [15., 16., 17., 18., 19.],
       [ 0.,  1.,  2.,  3.,  4.]])

0부터 연속된 정수로 이루어진 (2,10,10) 행렬 a를 생성, 텍스트 파일에 저장한 뒤 텍스트파일을 열어 내용 확인

In [237]:
ar = np.arange(200).reshape(2,10,10)
ar

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [240]:
np.savetxt('C:/data/file02.txt',ar)

ValueError: Expected 1D or 2D array, got 3D array instead

In [245]:
price = np.array([100,200,300])
qnt = np.array([5,25,50])
cal = price * qnt
cal
np.savetxt('c:/data/cal.txt', cal)

In [246]:
np.loadtxt('c:/data/cal.txt')

array([  500.,  5000., 15000.])

# 실습

In [281]:
ar = np.array([[1,70,85,95,100,100],[2,100,85,90,90,95],[3,95,95,80,70,70],[4,65,75,70,90,100],[5,90,80,85,95,95],[6,90,90,75,75,80],[7,60,90,80,40,45],[8,85,90,75,60,90],[9,90,85,85,90,85]])
ar

array([[  1,  70,  85,  95, 100, 100],
       [  2, 100,  85,  90,  90,  95],
       [  3,  95,  95,  80,  70,  70],
       [  4,  65,  75,  70,  90, 100],
       [  5,  90,  80,  85,  95,  95],
       [  6,  90,  90,  75,  75,  80],
       [  7,  60,  90,  80,  40,  45],
       [  8,  85,  90,  75,  60,  90],
       [  9,  90,  85,  85,  90,  85]])

In [317]:
ar_mean = np.mean(ar[0:,1:], axis=1)
ar_mean

array([90., 92., 82., 80., 89., 82., 63., 80., 87.])

전체 평균 높은 애 - 2번째 애

In [327]:
max_mean = np.argmax(ar_mean)
max_mean

1

전체 평균 낮은 애 - 7번째 애

In [319]:
np.argmin(ar_mean)

6

국어, 영어, 수학 점수 평균 가장 높은 애 (영어,국어,수학,체육,컴퓨터)

In [320]:
ar[0:,1:4]

array([[ 70,  85,  95],
       [100,  85,  90],
       [ 95,  95,  80],
       [ 65,  75,  70],
       [ 90,  80,  85],
       [ 90,  90,  75],
       [ 60,  90,  80],
       [ 85,  90,  75],
       [ 90,  85,  85]])

In [321]:
ar1 = np.mean(ar[0:,1:4], axis=1)
ar1

array([83.33333333, 91.66666667, 90.        , 70.        , 85.        ,
       85.        , 76.66666667, 83.33333333, 86.66666667])

In [328]:
np.argmax(ar1)
# 2번째 애

1

국어,영어,수학 점수에 2배 가중치를 주고 합계

In [294]:
base = ar[0:,1:4]
base

array([[ 70,  85,  95],
       [100,  85,  90],
       [ 95,  95,  80],
       [ 65,  75,  70],
       [ 90,  80,  85],
       [ 90,  90,  75],
       [ 60,  90,  80],
       [ 85,  90,  75],
       [ 90,  85,  85]])

In [295]:
ano = ar[0:,4:]
ano

array([[100, 100],
       [ 90,  95],
       [ 70,  70],
       [ 90, 100],
       [ 95,  95],
       [ 75,  80],
       [ 40,  45],
       [ 60,  90],
       [ 90,  85]])

In [306]:
gop2 = np.array([[2],[2],[2]])
gop1 = np.ones((2,1))
# gop3 = np.array()

In [307]:
total = (base@gop2) + (ano@gop1)

In [308]:
total

array([[700.],
       [735.],
       [680.],
       [610.],
       [700.],
       [665.],
       [545.],
       [650.],
       [695.]])

In [314]:
ar[np.argmax(total)][0]
# 총점이 가장 높은 학생의 학번

2

In [310]:
(base@gop2)

array([[500],
       [550],
       [540],
       [420],
       [510],
       [510],
       [460],
       [500],
       [520]])

In [309]:
(ano@gop1)

array([[200.],
       [185.],
       [140.],
       [190.],
       [190.],
       [155.],
       [ 85.],
       [150.],
       [175.]])